# Generated by Django 6.0.3 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_column='Department', max_length=100)),
                ('course_title', models.CharField(db_column='Course Title', max_length=200)),
                ('instructor', models.CharField(db_column='Instructor', max_length=100)),
            ],
            options={
                'db_table': 'Course_table',
            },
        ),
    ]
